version: "2"
run:
    timeout: 5m
    go: 1.26.2
    build-tags:
        - goexperiment.arenas
        - goexperiment.goroutineleakprofile
        - goexperiment.jsonv2
        - goexperiment.runtimesecret
        - goexperiment.simd
    allow-parallel-runners: true
    allow-serial-runners: true
    issues-exit-code: 1
    tests: true
output:
    formats: {}
linters:
    enable:
        - bodyclose
        - contextcheck
        - copyloopvar
        - cyclop
        - durationcheck
        - errchkjson
        - errname
        - errorlint
        - exhaustruct
        - forcetypeassert
        - funlen
        - gochecknoglobals
        - gochecknoinits
        - goconst
        - gocritic
        - gosec
        - gosmopolitan
        - loggercheck
        - nilnesserr
        - noctx
        - nolintlint
        - paralleltest
        - prealloc
        - revive
        - thelper
        - unparam
    settings:
        cyclop:
            max-complexity: 20
        funlen:
            max: 80
            min-lines: 1
        gosec:
            excludes:
                - G304
                - G204
                - G706
                - G115
formatters:
    enable:
        - gci
        - goimports
        - gofumpt
        - golines
issues:
    max-issues-per-linter: 50
    max-same-issues: 10
